"""add_warehouse_and_location_to_replenishments

Revision ID: 4b9cd66f8e2a
Revises: dbd6a122567d
Create Date: 2026-06-14 02:28:42.795843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9cd66f8e2a'
down_revision = 'dbd6a122567d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manufacturing_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=80), nullable=True))

    with op.batch_alter_table('procurement_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=80), nullable=True))

    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('warehouse')

    with op.batch_alter_table('procurement_requests', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('warehouse')

    with op.batch_alter_table('manufacturing_orders', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('warehouse')

    # ### end Alembic commands ###
