"""Add stock transfer and multi-location support

Revision ID: dbd6a122567d
Revises: 
Create Date: 2026-06-14 02:18:06.896187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd6a122567d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_number', sa.String(length=80), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('from_warehouse', sa.String(length=80), nullable=False),
    sa.Column('from_location', sa.String(length=80), nullable=False),
    sa.Column('to_warehouse', sa.String(length=80), nullable=False),
    sa.Column('to_location', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_number')
    )
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.create_unique_constraint('_product_warehouse_location_uc', ['product_id', 'warehouse', 'location'])

    with op.batch_alter_table('procurement_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_transfer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_procurement_requests_stock_transfers', 'stock_transfers', ['stock_transfer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procurement_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_procurement_requests_stock_transfers', type_='foreignkey')
        batch_op.drop_column('stock_transfer_id')

    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.drop_constraint('_product_warehouse_location_uc', type_='unique')

    op.drop_table('stock_transfers')
    # ### end Alembic commands ###
